// Generated by CoffeeScript 1.10.0
(function() {
  var _, args2, assert, equal, sampleFunction;

  args2 = require('../');

  assert = require('chai').assert;

  _ = require('lodash');

  equal = assert.deepEqual;

  sampleFunction = function() {
    var args;
    args = new args2(arguments);
    return {
      text1: args.str(),
      text2: args.str(false, 'default value'),
      n1: args.num(),
      obj1: args.obj(false, {}),
      arr1: args.array(false, []),
      bool1: args.bool(false, false),
      function1: args.func(true),
      other1: args.other(false, 1)
    };
  };

  describe("instance sample", function() {
    it("get arguments", function() {
      var res;
      res = sampleFunction('hello', 'world', 2, {
        hello: 'world'
      }, [3, 8], true, null, function() {
        return 999;
      });
      equal(res.text1, 'hello');
      equal(res.text2, 'world');
      equal(res.n1, 2);
      equal(res.obj1, {
        hello: 'world'
      });
      equal(res.arr1, [3, 8]);
      equal(res.bool1, true);
      equal(res.function1(), 999);
      return equal(res.other1, null);
    });
    it("get arguments(Another Order)", function() {
      var res;
      res = sampleFunction(true, null, 'hello', [3, 8], 2, {
        hello: 'world'
      }, 'world', function() {
        return 999;
      });
      equal(res.text1, 'hello');
      equal(res.text2, 'world');
      equal(res.n1, 2);
      equal(res.obj1, {
        hello: 'world'
      });
      equal(res.arr1, [3, 8]);
      equal(res.bool1, true);
      equal(res.function1(), 999);
      return equal(res.other1, null);
    });
    it("required argument - function1", function() {
      var fn;
      fn = function() {
        return sampleFunction();
      };
      return assert.throws(fn, 'Function argument required');
    });
    return it("default Value", function() {
      var fn, res;
      fn = function() {
        return 'value';
      };
      res = sampleFunction(fn);
      equal(res.text1, void 0);
      equal(res.text2, 'default value');
      equal(res.n1, void 0);
      equal(res.obj1, {});
      equal(res.arr1, []);
      equal(res.bool1, false);
      return equal(res.other1, 1);
    });
  });

  describe("alias", function() {
    return it("alias list", function() {
      equal(args2.prototype.string, args2.prototype.str);
      equal(args2.prototype.number, args2.prototype.num);
      equal(args2.prototype.object, args2.prototype.obj);
      equal(args2.prototype.arr, args2.prototype.array);
      equal(args2.prototype.boolean, args2.prototype.bool);
      equal(args2.prototype["function"], args2.prototype.func);
      return equal(args2.prototype.callback, args2.prototype.func);
    });
  });

  describe("bridge", function() {
    return it("bridge function", function() {
      var bridgeFunction, res1, res2;
      bridgeFunction = function() {
        return args2.bridge(arguments, sampleFunction);
      };
      res1 = bridgeFunction('test1', 1, 2, function() {
        return 999;
      });
      res2 = sampleFunction('test1', 1, 2, function() {
        return 999;
      });
      equal(res1.text1, res2.text1);
      equal(res1.text2, res2.text2);
      equal(res1.n1, res2.n1);
      equal(res1.obj1, res2.obj1);
      equal(res1.arr1, res2.arr1);
      equal(res1.bool1, res2.bool1);
      equal(res1.other1, res2.other1);
      return equal(res1.function1(), res2.function1());
    });
  });

}).call(this);
