// Generated by CoffeeScript 1.10.0
(function() {
  var _, args2, assert;

  args2 = require('../');

  assert = require('chai').assert;

  _ = require('lodash');

  describe("required test", function() {
    it("string required", function() {
      var fn, sampleFunction;
      sampleFunction = function() {
        var args, text1;
        args = new args2(arguments);
        return text1 = args.str(1);
      };
      fn = function() {
        return sampleFunction();
      };
      return assert.throws(fn, /String argument required/);
    });
    return it("custom error message", function() {
      var fn, sampleFunction;
      sampleFunction = function() {
        var args, text1;
        args = new args2(arguments);
        return text1 = args.str(1, 'undefined is not a valid uri or options object.');
      };
      fn = function() {
        return sampleFunction();
      };
      return assert.throws(fn, /undefined is not a valid uri or options object/);
    });
  });

}).call(this);
