// Generated by CoffeeScript 1.10.0

/*
example:
  args = Array::slice.call(arguments, 0)
  {nums,strs,objs,funcs,others} = argsConverter.apply(@,args)
 */

(function() {
  var _;

  _ = require('lodash');

  module.exports = function() {
    var args, res;
    args = Array.prototype.slice.call(this["arguments"], 0);
    res = {
      nums: [],
      strs: [],
      objs: [],
      funcs: [],
      others: []
    };
    args.forEach(function(item) {
      if (_.isNumber(item)) {
        return res.nums.push(item);
      } else if (_.isString(item)) {
        return res.strs.push(item);
      } else if (_.isPlainObject(item)) {
        return res.objs.push(item);
      } else if (_.isFunction(item)) {
        return res.funcs.push(item);
      } else {
        return res.others.push(item);
      }
    });
    return res;
  };

}).call(this);
